# Generated by Django 5.2.9 on 2025-12-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Registro Ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Campanha')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Objetivo')),
                ('meta_votos', models.PositiveIntegerField(default=0)),
                ('orcamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lideranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Registro Ativo')),
                ('votos_estimados', models.IntegerField(default=0)),
                ('meta_individual', models.IntegerField(default=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liderancas', to='core.campanha')),
            ],
            options={
                'verbose_name': 'Liderança',
                'ordering': ['-votos_estimados'],
            },
        ),
    ]
