# Generated by Django 5.2.9 on 2025-12-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleitores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleitores.eleitor')),
            ],
        ),
    ]
