# Generated by Django 5.2.9 on 2025-12-27 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_urna', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('partido', models.CharField(max_length=20)),
                ('cargo', models.CharField(default='Vereador', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario_root', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lideranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('COORDENADOR', 'Coordenador'), ('LIDER', 'Líder de Bairro'), ('VOLUNTARIO', 'Voluntário')], default='VOLUNTARIO', max_length=20)),
                ('municipio_base', models.CharField(max_length=100)),
                ('indicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.lideranca')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('titulo_eleitor', models.CharField(max_length=20, unique=True)),
                ('zona', models.CharField(max_length=10)),
                ('secao', models.CharField(max_length=10)),
                ('tags', models.CharField(help_text='Ex: Saúde, Igreja, Universitário', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('municipio', models.CharField(default='Salinópolis', max_length=100)),
                ('votos_no_domicilio', models.IntegerField(default=1)),
                ('data_visita', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.lideranca')),
            ],
        ),
    ]
