# Generated by Django 5.2.9 on 2025-12-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_urna', models.CharField(max_length=100, verbose_name='Nome de Urna')),
                ('numero', models.CharField(max_length=10, verbose_name='Número do Candidato')),
                ('partido', models.CharField(max_length=50, verbose_name='Partido')),
                ('cargo_disputado', models.CharField(max_length=100, verbose_name='Cargo em Disputa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Candidatura Ativa')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.DeleteModel(
            name='Campanha',
        ),
    ]
