# Generated by Django 5.2.9 on 2025-12-26 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lideranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('telefone', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('meta_votos', models.IntegerField(default=0, verbose_name='Meta de Votos')),
                ('nivel', models.CharField(choices=[('A', 'Influência Alta'), ('B', 'Influência Média'), ('C', 'Influência Local')], default='C', max_length=1, verbose_name='Nível')),
                ('biografia', models.TextField(blank=True, verbose_name='Dossiê Político')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.municipio', verbose_name='Município Base')),
            ],
            options={
                'verbose_name': 'Liderança',
                'verbose_name_plural': 'Lideranças',
            },
        ),
        migrations.CreateModel(
            name='AtendimentoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.TextField(verbose_name='Descrição do Pedido')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('E', 'Em Andamento'), ('C', 'Concluído')], default='P', max_length=20)),
                ('lideranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liderancas.lideranca', verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
    ]
