# Generated by Django 5.2.9 on 2025-12-26 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lideranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Liderança')),
                ('telefone', models.CharField(max_length=25, verbose_name='WhatsApp/Celular')),
                ('meta_votos', models.PositiveIntegerField(default=0, verbose_name='Potencial de Votos')),
                ('nivel', models.CharField(choices=[('A', 'Alta Prioridade'), ('B', 'Média'), ('C', 'Local')], default='C', max_length=1)),
                ('observacoes', models.TextField(blank=True, verbose_name='Notas de Campo')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='municipios.municipio', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Liderança',
                'verbose_name_plural': 'Lideranças',
            },
        ),
        migrations.CreateModel(
            name='AtendimentoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda', models.TextField(verbose_name='Pedido/Necessidade')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('concluido', models.BooleanField(default=False, verbose_name='Finalizado?')),
                ('lideranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liderancas.lideranca')),
            ],
            options={
                'verbose_name': 'Atendimento',
            },
        ),
    ]
