# Generated by Django 5.2.9 on 2025-12-26 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liderancas', '0001_initial'),
        ('municipios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lideranca',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderancas_rel', to='municipios.municipio'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lideranca_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimentosocial',
            name='lideranca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='liderancas.lideranca'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='regiao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='liderancas.regiaointegracao'),
        ),
    ]
