# Generated by Django 5.2.9 on 2025-12-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0001_initial'),
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentosocial',
            name='data_registro',
        ),
        migrations.RemoveField(
            model_name='lideranca',
            name='observacoes',
        ),
        migrations.AlterField(
            model_name='atendimentosocial',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Atendido?'),
        ),
        migrations.AlterField(
            model_name='atendimentosocial',
            name='demanda',
            field=models.TextField(verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='lideranca',
            name='meta_votos',
            field=models.PositiveIntegerField(default=0, verbose_name='Meta de Votos'),
        ),
        migrations.AlterField(
            model_name='lideranca',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='municipios.municipio', verbose_name='Cidade Base'),
        ),
        migrations.AlterField(
            model_name='lideranca',
            name='nivel',
            field=models.CharField(choices=[('A', 'Influência Alta'), ('B', 'Média'), ('C', 'Local')], default='C', max_length=1, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='lideranca',
            name='telefone',
            field=models.CharField(max_length=25, verbose_name='WhatsApp'),
        ),
    ]
